name: 'modern_lakehouse'
version: '1.0.0'
config-version: 2

profile: 'modern_lakehouse'

model-paths: ["models"]
seed-paths: ["../seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
docs-paths: ["../docs"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  modern_lakehouse:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: ephemeral
    marts:
      +materialized: table
      +schema: marts

seeds:
  modern_lakehouse:
    +schema: raw
